# Generated by Django 3.2.6 on 2024-11-20 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='capture_data',
            field=models.BooleanField(default=False, help_text='Whether to capture form submissions'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='redirect_url',
            field=models.URLField(blank=True, help_text='Optional URL to redirect users after form submission', null=True),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='content',
            field=models.TextField(help_text='HTML content of the landing page'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the page was created'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='title',
            field=models.CharField(help_text='Title of the landing page', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the page was last updated'),
        ),
        migrations.CreateModel(
            name='CapturedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_data', models.JSONField(help_text='Captured form submission data')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of form submission')),
                ('landing_page', models.ForeignKey(help_text='The landing page associated with this captured data', on_delete=django.db.models.deletion.CASCADE, related_name='captured_data', to='home.landingpage')),
            ],
        ),
    ]
