# Generated by Django 3.2.6 on 2024-11-21 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20241120_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='collect_emails',
            field=models.BooleanField(default=False, help_text='Enable email collection from the landing page'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='geolocation_tracking',
            field=models.BooleanField(default=False, help_text='Enable geolocation tracking of visitors'),
        ),
        migrations.CreateModel(
            name='VisitorAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the visitor')),
                ('geolocation_data', models.JSONField(blank=True, help_text='Geolocation data of the visitor', null=True)),
                ('visit_time', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the visit')),
                ('landing_page', models.ForeignKey(help_text='The landing page associated with this visitor data', on_delete=django.db.models.deletion.CASCADE, related_name='visitor_analytics', to='home.landingpage')),
            ],
        ),
    ]
