# Generated by Django 3.2.6 on 2024-11-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20241121_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='credential_harvesting',
            field=models.BooleanField(default=False, help_text='Enable credential harvesting from the landing page'),
        ),
    ]
