# Generated by Django 3.2.6 on 2024-12-18 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20241122_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the group', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the group was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the group was last updated')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="User's first name", max_length=255)),
                ('last_name', models.CharField(help_text="User's last name", max_length=255)),
                ('email', models.EmailField(help_text="User's email address", max_length=254, unique=True)),
                ('position', models.CharField(blank=True, help_text="User's job position", max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the user was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the user was last updated')),
                ('group', models.ForeignKey(help_text='Group to which the user belongs', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='home.group')),
            ],
        ),
    ]
