# Generated by Django 3.2.6 on 2024-12-19 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_group_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text="User's email address", max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AddIndex(
            model_name='captureddata',
            index=models.Index(fields=['submitted_at'], name='home_captur_submitt_9461ab_idx'),
        ),
        migrations.AddIndex(
            model_name='captureddata',
            index=models.Index(fields=['landing_page'], name='home_captur_landing_b02953_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['name'], name='home_group_name_3dfa33_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['created_at'], name='home_group_created_2fda38_idx'),
        ),
        migrations.AddIndex(
            model_name='landingpage',
            index=models.Index(fields=['created_at'], name='home_landin_created_03ec49_idx'),
        ),
        migrations.AddIndex(
            model_name='landingpage',
            index=models.Index(fields=['title'], name='home_landin_title_14ed72_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='home_user_email_536475_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['group'], name='home_user_group_i_ee3b22_idx'),
        ),
        migrations.AddIndex(
            model_name='visitoranalytics',
            index=models.Index(fields=['visit_time'], name='home_visito_visit_t_73605a_idx'),
        ),
        migrations.AddIndex(
            model_name='visitoranalytics',
            index=models.Index(fields=['landing_page'], name='home_visito_landing_33d770_idx'),
        ),
    ]
