# Generated by Django 5.1.4 on 2024-12-31 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20241219_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('envelope_sender', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('use_tracker', models.BooleanField(default=False)),
                ('text_content', models.TextField()),
                ('html_content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
